### ISSUE TITLE
Dockerhub API change breaks tag lookup

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-version-number-provider#13]
Looks like dockerhub changed their API / obsoleted version 1:
```
String dockerVersion = "exasol/docker-db:"
                + assertDoesNotThrow(
                () -> new ExasolVersionNumberProviderFactory()
                        .buildExasolVersionNumberProvider()
                        .getLatestReleaseForMinor(7, 1)
        );

...
java.io.FileNotFoundException: https://registry.hub.docker.com/v1/repositories/exasol/docker-db/tags
```

https://github.com/exasol/exasol-version-number-provider/blob/a178d86f25ab894a661a033c754a29d45c46b014/src/main/java/com/exasol/versionnumberprovider/ExasolVersionNumberProviderFactory.java#L20

Same URL with `/v2/` returns a result.

**Comment by kaklakariada** [comment]
@exaSR thank you for reporting this!
Version [0.2.4](https://github.com/exasol/exasol-version-number-provider/releases/tag/0.2.4) fixes this issue.
